=== PurdueElectricRacing/daqapp/hil_config/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",

  "required": ["name", "description", "expect"],

  "properties": {
	"$schema": {
	  "type": "string"
	},

    "name": {
      "type": "string"
    },

    "description": {
      "type": "string"
    },

    "tx": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["timestamp", "msg_name", "signals"],

        "properties": {
          "timestamp": {
            "type": "number"
          },

          "msg_name": {
            "type": "string"
          },

          "signals": {
            "type": "object",
            "additionalProperties": {
              "type": "number"
            }
          }
        },

        "additionalProperties": false
      }
    },

    "expect": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["window", "msg_name"],

        "properties": {
          "window": {
			"type": "array",
			"items": {
			  "type": "number"
			},
			"minItems": 2,
			"maxItems": 2
		  },

          "msg_name": {
            "type": "string"
          },

          "signals": {
            "type": "object",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "number"
              },
              "minItems": 2,
              "maxItems": 2
            }
          }
        },

        "additionalProperties": false
      }
    }
  },

  "additionalProperties": false
}

=== PurdueElectricRacing/daqapp/hil_config/tests/idk.json
{
	"$schema": "../schema.json",

	"name": "Pack sanity check",
	"description": "Verify thermistor response",

	"tx": [
		{
			"timestamp": 15,
			"msg_name": "pack_stats",
			"signals": {
				"pack_voltage": 540.0,
				"pack_current": 10.0,
				"max_temp": 35.0
			}
		}
	],
	"expect": [
		{
			"window": [15, 20],
			"msg_name": "thermistor_telemetry",
			"signals": {
				"temperature": [30.0, 40.0]
			}
		}
	]
}
